site_name: Python for Machine Learning
site_author: Rudra Prasad Bhuyan
site_description: A collection of Python resources for Machine Learning
site_url: https://github.com/Rudra-G-23/python-for-machine-learning
repo_url: https://github.com/Rudra-G-23/python-for-machine-learning
repo_name: Rudra-G-23/python-for-machine-learning
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Rudra Prasad Bhuyan. All rights reserved.

# Theme
theme:
  name: material
  icon:
    annotation: material/star-four-points-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    #- content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate

  palette:
    - scheme: default
      primary: '#5e17eb'   
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: '#5e17eb'
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/language-python

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      enable_git_follow: false

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Social Media Links 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rudra-G-23/
      name: Github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Rudra_love_with_data
      name: YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rudra-prasad-bhuyan-44a388235/
      name: LinkedIn
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/rudraprasadbhuyan
      name: Kaggle
    - icon: fontawesome/brands/pinterest
      link: https://in.pinterest.com/rudraprasadbhuyan23
      name: Pinterest

nav:
  - Home: index.md
  - Basic:
      - Python Basics: basic-concepts/python-basic.md
      - Loops: basic-concepts/loop-1.md
      - Pattern: basic-concepts/loop-2.md
  - Data Structures:
      - String: data-structures/string.md
      - List: data-structures/list.md
      - Tuple: data-structures/tuple.md
      - Set: data-structures/set.md
      - Dictionary: data-structures/dictionary.md
  - OOP:
      - Functions: oop/functions.md
      - Cool Functions: oop/cool-functions.md
      - Abstraction: oop/abstraction.md
      - Encapsulation: oop/encapsulation.md
      - Inheritance: oop/inheritance.md
      - Polymorphism: oop/polymorphism.md
  - Intermediate:
      - Overview: intermediate-python/index.md